### ISSUE TITLE
Not working with the ESX framework

### ISSUE THREAD

**Issue by Xorbite** [minobear/esx_giveownedcar#3]
Greetings,

As of lately, I have implemented this script into my server only to see that it doesn't really work properly and I really do need something like this that supports the ESX framework I'm working with. I'm using ESX V1.3, if you could help me out I would really appreciate it. Thanks overall for making this script possible but I just need it to work with ESX and not essentialmode :>

**Comment by minobear** [comment]
@DarkProvider Any errors happened on server or client side?

**Comment by Xorbite** [comment]
There are no errors shown unfortunately

**Comment by Xorbite** [comment]
The command is not being registered sadly and therefore there is nothing appearing

**Comment by minobear** [comment]
you can use command on console:
```
_givecar [playerID] [vehicle] <plate>
_delcarplate <plate>
```

**Comment by minobear** [comment]
@DarkProvider Updated:
https://forum.cfx.re/t/release-esx-give-or-delete-car-to-owned-vehicle-database-plate-can-custom-or-random-generate/1050821/72?u=mino1

**Comment by Xorbite** [comment]
Is it possible to use Aceperms instead of specifiying the steam ID's?

**Comment by minobear** [comment]
add this ``giveownedcar.command``

**Comment by Xorbite** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/53404124/98327390-a6bf4900-1ff3-11eb-91c9-a32d0ebf1d98.jpg)
Also, this is what I meant by not registered btw

**Comment by Xorbite** [comment]
The issue is still the same sadly

**Comment by minobear** [comment]
Have you tried execute the command on console? (prefix change to _)

**Comment by Xorbite** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/53404124/98401737-749aff00-2066-11eb-8ad1-a6017a7a0db8.jpg)
Still not being recognized

**Comment by Xorbite** [comment]
Any updates mate?

**Comment by minobear** [comment]
but I don't have this problem
the command is work on my test >:

**Comment by Xorbite** [comment]
That's so strange, what version of ESX are you using? And do you use essentialmode with it?

**Comment by Xorbite** [comment]
I'm using version 1.3 which is the latest first version of ESX without essentialmode

**Comment by minobear** [comment]
But I using FiveM Native ``RegisterCommand`` to register command it should be work without ESX

**Comment by Xorbite** [comment]
That's weird actually
