### ISSUE TITLE
SCRIPT ERROR: @esx_givevehicle/server/main.lua:166: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by heavenlygamer04** [minobear/esx_giveownedcar#5]
Hi! i installed this on my dedicated server and when i do "/givecar 1 bolide test" (that is my character id, and i do have a car with that model name) i get this error: SCRIPT ERROR: @esx_givevehicle/server/main.lua:166: attempt to index a nil value (local 'xPlayer')

I have admin (not superadmin). 

Thanks in advance!

**Comment by minobear** [comment]
Where do you use this command?
on client or server?

**Comment by heavenlygamer04** [comment]
both. same error except in game it says i dont have perms aswell as pops the error in the console.

**Comment by heavenlygamer04** [comment]
nevermind, i switched everything over to a different pc and it works now. thanks for the amazing script!
